### ISSUE TITLE
On ipad and smaller screen sizes, the table headers remain sticky when you scroll down.

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/DataTables#1]
When you scroll past the table, the table headers stick to the top of the screen, overlapping the lower content.

**Comment by Mackenzie-Cope** [comment]
This happens to all the datatables publication lists on smaller sizes.

**Comment by marshallrobinson** [comment]
This was caused by setting the "fixedHeader" property to "true". Setting it to "false" fixes it.
