### ISSUE TITLE
check energy & minerals datatables publication list

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/DataTables#8]
The first draft of the dynamic emp pubs list is done. There are some test publications in there with the correct keywords to test the filters. @marshallrobinson will you take a look and give me some feedback? I'll ask Martha to do an insert for the rest of the keywords on the repository afterward.

Draft Page: https://geology.utah.gov/?page_id=46081&preview=1&_ppp=27a34a1e8b (link expires August 10th)

**Comment by marshallrobinson** [comment]
Looks great! Good work!
