### ISSUE TITLE
Keywords insert into mysql for Energy & Mineral Pubs

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/DataTables#9]
We need to add keywords to mysql for all the Energy and Mineral pubs. I think I remember in the past we have used only the series ID to match the items and then insert the keywords in addition to any existing keywords already in mysql. 

I've attached the xlsx of all the new keywords that need to go in. Let me know if I need to review any of the data or test anything before it is live. Or if you need a csv instead I can email it to you, Martha. Thanks!

[emppubsKEYWORDS.xlsx](https://github.com/UGS-GIO/DataTables/files/6927289/emppubsKEYWORDS.xlsx)

**Comment by marthajensen** [comment]
@Mackenzie-Cope 

I inserted the Energy and Mineral keywords into a new table named 'test'. Please check the new table and make sure everything looks good. Once you are ready let me know and I'll insert the keywords into the main 'UGSpubs' table. Thank you Mackenzie!

**Comment by Mackenzie-Cope** [comment]
@marthajensen 

Looked good when I tested the filtered list from "test." You can insert them into the main "UGSpubs" table. Thanks!

**Comment by marthajensen** [comment]
@Mackenzie-Cope The energy min keywords were inserted into the "UGSpubs" table. Please let me know if you see any issues.

:)

**Comment by Mackenzie-Cope** [comment]
Looks great, Thanks!
